services:
  memorylane:
    build: .
    hostname: memorylane
    container_name: memorylane
    restart: unless-stopped
    ports:
      - "4173:4173"
    volumes:
      - memorylane_images:/app/images
      - memorylane_exports:/app/exports

    environment:
      - NODE_ENV=production

volumes:
  memorylane_images:
  memorylane_exports: